name: Go
on: [push]

jobs:
  build:
    
    strategy:
      matrix:
        platform: [ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.platform }}

    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.21.3'
      
      - run: go version
      
      - run: go env -w CGO_ENABLED=0

      - run: go env
      
      - name: Install dependencies
        run: cd golang-basic-cred && go get .

      - name: Install dependencies
        run: cd credmanager && go get .
      
      - name: Build
        run: go build -v ./credmanager

      - name: Build
        run: go build -v ./golang-basic-cred
      
      - name: Test with the Go CLI
        run: cd ./golang-basic-cred && go test -v
